# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://frostilia.github.io
date_format: "ordinal"
title: "Frostilia's Blog"
subtitle: "A simple blog"
description: "Frostilia's personal blog"
keywords: frostilia, blog
timezone: Asia/Taipei
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Frostilia
organization: 
organization_url: 
github_username: Frostilia
location: Taiwan
email: anja.ancerade@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首頁/HomePage

  -
    href: /categories/
    label: 分類/Categories

#   -
#     href: /archives/
#     label: 归档

  # -
    # href: /wiki/
    # label: 维基

  -
    href: /links/
    label: 聯接/Links

  # -
    # href: /about/
    # label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: frostilia/frostilia.github.io

# ---------------- #
     # Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
# comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
    # username: 
# https://imsun.net/posts/gitment-introduction/
# gitment:
    # owner: Ruhisoles
    # repo: blog-comments
    # oauth:
        # client_id: Iv1.c9a20c048a0953c8
        # client_secret: 265a1c3d343d59b60cc64bc6a66b93f04e21b0c7
# https://github.com/gitalk/gitalk#install
# gitalk:
    # owner: Ruhisoles
    # repo: blog-comments
    # clientID: Iv1.c9a20c048a0953c8
    # clientSecret: 265a1c3d343d59b60cc64bc6a66b93f04e21b0c7
# 在使用其它评论组件时可点击显示 Disqus
# lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#     analytics_id: UA-159646626-1
